import { useEffect,useState } from "react";
import { Link,useLocation,useNavigate } from "react-router-dom";
import { BarChart3,BriefcaseBusiness,FileText,Gem,History,LayoutDashboard,Megaphone,Settings2,ShieldAlert,Users,WalletCards } from "lucide-react";
import { LineChart,Line,ResponsiveContainer,XAxis,YAxis,Tooltip,Legend } from "recharts";
import VillageShell from "@/components/VillageShell";
import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";import {Badge} from "@/components/ui/badge";import {api,post,patch,del} from "@/lib/api";import {useAuth} from "@/lib/auth";
const money=(c:number)=>`$${(c/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const sections=[["Overview","/admin",LayoutDashboard],["Users","/admin/users",Users],["Deposits","/admin/deposits",WalletCards],["Withdrawals","/admin/withdrawals",WalletCards],["Transfers","/admin/transfers",History],["Transactions","/admin/transactions",History],["Diamond Reserves","/admin/diamond-reserves",Gem],["Economy","/admin/economy",BarChart3],["Economy Charts","/admin/economy/charts",BarChart3],["News Network","/admin/news",Megaphone],["Jobs Network","/admin/jobs",BriefcaseBusiness],["Job Applications","/admin/job-applications",FileText],["Audit Log","/admin/audit-log",FileText],["System Diagnostics","/admin/system",Settings2]] as const;

export default function Admin(){
  const {user,loading}=useAuth(); const nav=useNavigate(); const loc=useLocation();
  const [data,setData]=useState<any>(null); const [msg,setMsg]=useState(""); const [search,setSearch]=useState("");
  async function refresh(){ try{ setData(await api("/admin/overview")); setMsg(""); } catch(e:any){ setMsg(e.message); } }
  useEffect(()=>{ if(user?.role==="admin") void refresh(); },[user]);
  if(loading) return <Gate title="Checking admin access…"/>;
  if(!user){ nav("/"); return null; }
  if(user.role!=="admin"||user.status!=="active") return <Gate title="Access denied"/>;
  if(!data) return <Gate title={msg||"Loading Admin Console…"}/>;

  const section=loc.pathname==="/admin"?"overview":loc.pathname.split("/")[2]||"overview";
  const users=data.village_users||[], accounts=data.village_accounts||[], tx=data.village_transactions||[];
  const deps=data.village_deposit_requests||[], wds=data.village_withdrawal_requests||[], trs=data.village_transfers||[];
  const news=data.village_news||[], jobs=data.village_jobs||[], apps=data.village_applications||[], audit=data.village_audit_logs||[];
  const reserveTx=data.village_reserve_transactions||[], snaps=data.village_economy_snapshots||[], eco=data.economy||{};
  const filtered=users.filter((x:any)=>`${x.username} ${x.display_name||""}`.toLowerCase().includes(search.toLowerCase()));

  async function userAction(action:string,id:string,extra:any={}){ try{ await post(`/admin/users/${id}/${action}`,extra); await refresh(); } catch(e:any){setMsg(e.message)} }
  async function adjust(id:string,kind:string){ const v=prompt(kind==="set"?"New balance in dollars":"Amount in dollars"); const reason=prompt("Reason"); if(!v||!reason)return; try{ await post("/admin/balance/adjust",{user_id:id,kind,amount_cents:Math.round(Number(v)*100),reason}); await refresh(); } catch(e:any){setMsg(e.message)} }
  async function createUser(){ const username=prompt("Minecraft username"); const password=prompt("Temporary password (8+ characters)"); if(!username||!password)return; try{await post("/admin/users/create",{username,password});await refresh()}catch(e:any){setMsg(e.message)} }
  async function reviewRequest(kind:"deposits"|"withdrawals",x:any,action:string){const reason=prompt("Reason (optional)")||"";try{await post(`/admin/${kind}/${x.id}/${action}`,{reason});await refresh()}catch(e:any){setMsg(e.message)}}
  async function createTransfer(){ const from=prompt("Sender username"),to=prompt("Recipient username"),amount=prompt("Amount in dollars"),reason=prompt("Reason"); const s=users.find((x:any)=>x.username.toLowerCase()===from?.toLowerCase()),r=users.find((x:any)=>x.username.toLowerCase()===to?.toLowerCase()); if(!s||!r||!amount||!reason){setMsg("Valid sender, recipient, amount and reason required.");return;} try{await post("/admin/transfers",{sender_user_id:s.id,recipient_user_id:r.id,amount_cents:Math.round(Number(amount)*100),reason});await refresh()}catch(e:any){setMsg(e.message)} }
  async function adjustReserve(){ const amount=prompt("Diamond adjustment. Use negative to remove."); const reason=prompt("Reason"); if(!amount||!reason)return; try{await post("/admin/reserves/adjust",{amount:Number(amount),reason});await refresh()}catch(e:any){setMsg(e.message)} }
  async function changeRate(){ const rate=prompt("Dollars per diamond"); if(!rate)return; try{await post("/admin/economy/rate",{rate_cents:Math.round(Number(rate)*100)});await refresh()}catch(e:any){setMsg(e.message)} }

  let panel:any;
  if(section==="overview") panel=<Overview users={users} accounts={accounts} deps={deps} wds={wds} trs={trs} eco={eco} news={news} jobs={jobs}/>;
  else if(section==="users"||section==="accounts") panel=<UsersPanel users={filtered} accounts={accounts} act={userAction} adjust={adjust} create={createUser}/>;
  else if(section==="deposits") panel=<Requests title="Deposits" rows={deps} users={users} act={(x:any,a:string)=>reviewRequest("deposits",x,a)}/>;
  else if(section==="withdrawals") panel=<Requests title="Withdrawals" rows={wds} users={users} act={(x:any,a:string)=>reviewRequest("withdrawals",x,a)}/>;
  else if(section==="transfers") panel=<Transfers rows={trs} users={users} onCreate={createTransfer}/>;
  else if(section==="transactions") panel=<SimpleTable rows={tx.map((x:any)=>[x.username,String(x.type).replaceAll("_"," "),money(Number(x.amount_cents||0)),x.status])}/>;
  else if(section==="diamond-reserves") panel=<Reserve eco={eco} rows={reserveTx} onAdjust={adjustReserve}/>;
  else if(section==="economy"||section==="economy/charts") panel=<Economy eco={eco} snaps={snaps} onRate={changeRate}/>;
  else if(section==="news") panel=<ContentManager kind="news" rows={news} refresh={refresh} setMsg={setMsg}/>;
  else if(section==="jobs") panel=<ContentManager kind="jobs" rows={jobs} refresh={refresh} setMsg={setMsg}/>;
  else if(section==="job-applications") panel=<Applications rows={apps} patchApp={async(id:string,status:string)=>{try{await patch(`/admin/applications/${id}`,{status});await refresh()}catch(e:any){setMsg(e.message)}}}/>;
  else if(section==="audit-log") panel=<SimpleTable rows={audit.map((x:any)=>[x.actor,x.action,x.target||"",new Date(x.created_at).toLocaleString()])}/>;
  else if(section==="system") panel=<Diagnostics data={data}/>;
  else panel=<Card className="mt-8"><CardContent className="p-6">This section is managed through the connected systems above.</CardContent></Card>;

  return <VillageShell><div className="mx-auto grid max-w-[1500px] grid-cols-1 md:grid-cols-[245px_1fr]"><aside className="border-b bg-white p-4 md:min-h-[calc(100vh-73px)] md:border-r md:p-5"><p className="mb-3 px-3 text-xs font-semibold uppercase tracking-wide text-[#8b6b2e]">Control room</p><nav className="grid grid-cols-2 gap-1 md:grid-cols-1">{sections.map(([label,path,Icon])=><Link key={path} to={path} className={`flex min-h-10 items-center gap-3 rounded-lg px-3 text-sm ${loc.pathname===path?"bg-[#eaf1eb] font-semibold text-[#1b4d39]":"text-[#68766e] hover:bg-[#f2f6f2]"}`}><Icon size={16}/>{label}</Link>)}</nav></aside><main className="min-w-0 p-5 md:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-wide text-[#8b6b2e]">Village banking</p><h1 className="mt-2 font-display text-4xl capitalize">{section.replaceAll("-"," ")}</h1></div><div className="flex gap-2"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records" className="h-10 bg-white md:w-72"/><Button variant="outline" onClick={refresh}>Refresh</Button></div></div>{msg&&<p className="mt-5 rounded-xl bg-[#f4e7e5] px-4 py-3 text-sm text-[#963f35]">{msg}</p>}{panel}</main></div></VillageShell>;
}
function Gate({title}:{title:string}){return <div className="grid min-h-screen place-items-center bg-[#f5f7f3]"><Card><CardContent className="p-8 text-center"><ShieldAlert className="mx-auto text-[#963f35]"/><h1 className="mt-4 font-display text-3xl">{title}</h1></CardContent></Card></div>}
function Overview({users,accounts,deps,wds,trs,eco,news,jobs}:any){const c=[["Users",users.length],["Accounts",accounts.length],["Currency in circulation",money(eco.currency_supply_cents||0)],["Diamonds in reserve",`${eco.diamond_count||0} Diamonds`],["Reserve value",money(eco.reserve_value_cents||0)],["Backing",eco.backing_ratio==null?"N/A":`${Number(eco.backing_ratio).toFixed(1)}%`],["Pending deposits",deps.filter((x:any)=>x.status==="pending").length],["Pending withdrawals",wds.filter((x:any)=>x.status==="pending").length],["Transfers",trs.length],["News",news.length],["Jobs",jobs.length]];return <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{c.map(([a,b])=><Card key={String(a)}><CardContent className="p-5"><p className="text-sm text-[#758279]">{a}</p><p className="mt-3 font-display text-2xl">{b}</p></CardContent></Card>)}</div>}
function UsersPanel({users,accounts,act,adjust,create}:any){return <Card className="mt-8"><CardHeader className="flex-row items-center justify-between"><CardTitle>Users</CardTitle><Button onClick={create}>Create user</Button></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b text-left"><th className="pb-3">Username</th><th>Role</th><th>Status</th><th>Banking</th><th>Balance</th><th>Actions</th></tr></thead><tbody className="divide-y">{users.map((u:any)=>{const a=accounts.find((x:any)=>x.user_id===u.id);return <tr key={u.id}><td className="py-4 font-medium">{u.username}</td><td>{u.role}</td><td>{u.status}</td><td>{u.banking_status}</td><td>{money(Number(a?.balance_cents||0))}</td><td className="flex flex-wrap gap-2 py-2"><Button size="sm" variant="outline" onClick={()=>act(u.banking_status==="frozen"?"unfreeze":"freeze",u.id,{reason:"Admin action"})}>{u.banking_status==="frozen"?"Unfreeze":"Freeze"}</Button><Button size="sm" variant="outline" onClick={()=>act(u.status==="suspended"?"unsuspend":"suspend",u.id)}>{u.status==="suspended"?"Unsuspend":"Suspend"}</Button><Button size="sm" variant="outline" onClick={()=>{const p=prompt("New temporary password");if(p)act("reset-password",u.id,{password:p})}}>Reset password</Button><Button size="sm" variant="outline" onClick={()=>{const r=prompt("Role: user or admin",u.role);if(r)act("role",u.id,{role:r})}}>Role</Button><Button size="sm" variant="outline" onClick={()=>adjust(u.id,"add")}>Add $</Button><Button size="sm" variant="outline" onClick={()=>adjust(u.id,"remove")}>Remove $</Button><Button size="sm" variant="outline" onClick={()=>adjust(u.id,"set")}>Set balance</Button></td></tr>})}</tbody></table></div></CardContent></Card>}
function Requests({title,rows,users,act}:any){return <Card className="mt-8"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{rows.length?rows.map((x:any)=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#f3f6f3] p-4" key={x.id}><span>{users.find((u:any)=>u.id===x.user_id)?.username||"Unknown"} · {x.diamond_count} Diamonds · {x.status}</span>{x.status==="pending"&&<span className="flex gap-2"><Button size="sm" onClick={()=>act(x,"approve")}>Approve</Button><Button size="sm" variant="outline" onClick={()=>act(x,"reject")}>Reject</Button></span>}</div>):<p>No requests yet.</p>}</CardContent></Card>}
function Transfers({rows,users,onCreate}:any){return <><Button className="mt-8" onClick={onCreate}>New admin transfer</Button><SimpleTable rows={rows.map((x:any)=>[users.find((u:any)=>u.id===x.sender_user_id)?.username||"Unknown",`to ${users.find((u:any)=>u.id===x.recipient_user_id)?.username||"Unknown"}`,money(Number(x.amount_cents||0)),x.status])}/></>}
function Reserve({eco,rows,onAdjust}:any){return <Card className="mt-8"><CardHeader><CardTitle>Diamond reserves</CardTitle></CardHeader><CardContent><p className="font-display text-5xl">{eco.diamond_count||0} Diamonds</p><Button className="mt-5" onClick={onAdjust}>Adjust reserves</Button><p className="mt-5 text-sm text-[#68766e]">{rows.length} reserve movements recorded.</p></CardContent></Card>}
function Economy({eco,snaps,onRate}:any){const data=snaps.map((x:any)=>({date:new Date(x.created_at).toLocaleDateString(),currency:Number(x.currency_supply_cents||0)/100,reserve:Number(x.reserve_value_cents||0)/100}));return <div className="mt-8 space-y-5"><div className="grid gap-4 md:grid-cols-4"><Card><CardContent className="p-5"><p>Currency supply</p><b>{money(eco.currency_supply_cents||0)}</b></CardContent></Card><Card><CardContent className="p-5"><p>Reserve value</p><b>{money(eco.reserve_value_cents||0)}</b></CardContent></Card><Card><CardContent className="p-5"><p>Backing</p><b>{eco.backing_ratio==null?"N/A":`${Number(eco.backing_ratio).toFixed(1)}%`}</b></CardContent></Card><Card><CardContent className="p-5"><p>Rate</p><b>{money(eco.diamond_rate_cents||0)}</b><Button size="sm" variant="outline" className="mt-2" onClick={onRate}>Change</Button></CardContent></Card></div><Card><CardContent className="p-5"><h2 className="font-display text-2xl">Economy history</h2><div className="mt-4 h-80">{data.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={data}><XAxis dataKey="date" hide/><YAxis/><Tooltip/><Legend/><Line dataKey="currency" name="Currency supply" stroke="currentColor"/><Line dataKey="reserve" name="Reserve value" strokeDasharray="5 5" stroke="currentColor"/></LineChart></ResponsiveContainer>:<p>No economy history yet.</p>}</div></CardContent></Card></div>}
async function fileToData(file:File){return await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
function ContentManager({kind,rows,refresh,setMsg}:any){const create=async()=>{const title=prompt(`New ${kind==="news"?"article":"job"} title`);if(!title)return;try{await post(`/admin/${kind}`,{title,status:kind==="news"?"draft":"draft"});await refresh()}catch(e:any){setMsg(e.message)}};const upload=async(row:any,file:File)=>{try{const data=await fileToData(file);const up=await post<any>("/admin/media/upload",{filename:file.name,mime:file.type,data});await patch(`/admin/${kind}/${row.id}`,{image_url:up.url});await refresh()}catch(e:any){setMsg(e.message)}};return <Card className="mt-8"><CardHeader className="flex-row justify-between"><CardTitle>{kind==="news"?"News Network":"Jobs Network"}</CardTitle><Button onClick={create}>Create</Button></CardHeader><CardContent className="space-y-3">{rows.length?rows.map((x:any)=><div className="flex flex-wrap items-center justify-between gap-2 border-b pb-3" key={x.id}><span>{x.title} · {x.status}</span><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-md border px-3 py-2 text-xs">Upload image<input className="hidden" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)upload(x,f)}}/></label><Button size="sm" variant="outline" onClick={async()=>{const s=x.status==="published"||x.status==="open"?"draft":kind==="news"?"published":"open";await patch(`/admin/${kind}/${x.id}`,{status:s});await refresh()}}>{x.status==="published"||x.status==="open"?"Unpublish":"Publish"}</Button><Button size="sm" variant="outline" onClick={async()=>{if(confirm("Delete permanently?")){await del(`/admin/${kind}/${x.id}`);await refresh()}}}>Delete</Button></div></div>):<p>No content yet.</p>}</CardContent></Card>}
function Applications({rows,patchApp}:any){return <Card className="mt-8"><CardContent className="space-y-3 p-5">{rows.length?rows.map((x:any)=><div key={x.id} className="flex justify-between border-b pb-3"><span>{x.applicant} · {x.job_title} · {x.status}</span><span className="flex gap-2"><Button size="sm" onClick={()=>patchApp(x.id,"accepted")}>Accept</Button><Button size="sm" variant="outline" onClick={()=>patchApp(x.id,"rejected")}>Reject</Button></span></div>):<p>No applications yet.</p>}</CardContent></Card>}
function SimpleTable({rows}:any){return <Card className="mt-8"><CardContent className="p-5">{rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><tbody>{rows.map((r:any[],i:number)=><tr className="border-b" key={i}>{r.map((v,j)=><td className="py-3 pr-4" key={j}>{String(v??"")}</td>)}</tr>)}</tbody></table></div>:<p>No data yet.</p>}</CardContent></Card>}
function Diagnostics({data}:any){const checks=[["Server API","Working","Admin API returned"],["Users",data.village_users?.length?"Working":"Warning",`${data.village_users?.length||0} records`],["Accounts",data.village_accounts?.length?"Working":"Warning",`${data.village_accounts?.length||0} records`],["Transactions","Working",`${data.village_transactions?.length||0} records`],["Deposits","Working",`${data.village_deposit_requests?.length||0} records`],["Withdrawals","Working",`${data.village_withdrawal_requests?.length||0} records`],["Reserves",data.economy?.diamond_count?"Working":"Warning",`${data.economy?.diamond_count||0} Diamonds`],["News","Working",`${data.village_news?.length||0} records`],["Jobs","Working",`${data.village_jobs?.length||0} records`]];return <Card className="mt-8"><CardHeader><CardTitle>System diagnostics</CardTitle></CardHeader><CardContent className="space-y-3">{checks.map(r=><div className="grid grid-cols-[1fr_auto_1fr] gap-3 border-b pb-3" key={r[0]}><span>{r[0]}</span><Badge variant="outline">{r[1]}</Badge><span className="text-sm text-[#68766e]">{r[2]}</span></div>)}</CardContent></Card>}
