import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { ArrowRightLeft } from "lucide-react";
import VillageShell from "@/components/VillageShell";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { api,post } from "@/lib/api";
import { useAuth } from "@/lib/auth";
const money=(c:number)=>`$${(c/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function Banking(){const {user,loading}=useAuth();const nav=useNavigate();const loc=useLocation();const [data,setData]=useState<any>(null);const [error,setError]=useState("");async function refresh(){try{setData(await api("/me/banking"));setError("")}catch(e:any){setError(e.message)}}useEffect(()=>{if(user)void refresh()},[user]);if(loading)return <Center text="Checking session…"/>;if(!user){nav("/");return null}if(error)return <Center text={error}/>;if(!data)return <Center text="Loading banking…"/>;const page=loc.pathname.slice(1);return <VillageShell><main className="mx-auto max-w-6xl px-5 py-8 md:px-8"><div><p className="text-sm font-semibold uppercase tracking-wide text-[#8b6b2e]">Village banking</p><h1 className="mt-2 font-display text-4xl capitalize">{page}</h1><p className="mt-2 text-[#68766e]">Balance {money(data.balance_cents||0)} · {money(data.diamond_rate_cents||0)} per Diamond</p></div>{page==="send"?<Send data={data} refresh={refresh}/>:page==="deposit"?<Request kind="deposit" data={data} refresh={refresh}/>:page==="withdraw"?<Request kind="withdrawal" data={data} refresh={refresh}/>:<Transactions data={data}/>}</main></VillageShell>}
function Send({data,refresh}:{data:any;refresh:()=>Promise<void>}){const [recipient,setRecipient]=useState("");const [amount,setAmount]=useState("");const [note,setNote]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);async function submit(){setBusy(true);setMsg("");try{await post("/transfers/send",{recipient_user_id:recipient,amount_cents:Math.round(Number(amount)*100),note});setMsg("Transfer complete.");setAmount("");setNote("");await refresh()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}return <Card className="mt-8 max-w-2xl"><CardHeader><CardTitle>Send money</CardTitle></CardHeader><CardContent className="space-y-4"><Label>Recipient<select value={recipient} onChange={e=>setRecipient(e.target.value)} className="mt-2 h-11 w-full rounded-md border bg-white px-3"><option value="">Choose player</option>{data.recipients.map((x:any)=><option key={x.id} value={x.id}>{x.username}{x.display_name?` — ${x.display_name}`:""}</option>)}</select></Label><Label>Amount<Input className="mt-2" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Label><Label>Note<Input className="mt-2" value={note} onChange={e=>setNote(e.target.value)}/></Label>{msg&&<p className="text-sm">{msg}</p>}<Button disabled={busy||!recipient} onClick={submit} className="w-full bg-[#1b4d39]"><ArrowRightLeft size={16}/>{busy?"Sending…":"Send money"}</Button></CardContent></Card>}
function Request({kind,data,refresh}:{kind:"deposit"|"withdrawal";data:any;refresh:()=>Promise<void>}){const [diamonds,setDiamonds]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const count=Math.floor(Number(diamonds)||0);const amount=count*Number(data.diamond_rate_cents||0);async function submit(){setBusy(true);setMsg("");try{await post(`/${kind==="deposit"?"deposits":"withdrawals"}/request`,{diamond_count:count});setMsg(`${kind==="deposit"?"Deposit":"Withdrawal"} request submitted.`);setDiamonds("");await refresh()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}const items=kind==="deposit"?data.deposits:data.withdrawals;return <div className="mt-8 grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>{kind==="deposit"?"Deposit diamonds":"Withdraw diamonds"}</CardTitle></CardHeader><CardContent className="space-y-4"><Label>Diamonds<Input className="mt-2" type="number" min="1" step="1" value={diamonds} onChange={e=>setDiamonds(e.target.value)}/></Label><div className="rounded-xl bg-[#eef3ef] p-4">{kind==="deposit"?"Expected credit":"Currency cost"}: <b>{money(amount)}</b></div>{msg&&<p className="text-sm">{msg}</p>}<Button disabled={busy||count<1} onClick={submit} className="w-full bg-[#1b4d39]">{busy?"Submitting…":"Submit request"}</Button></CardContent></Card><Card><CardHeader><CardTitle>Your requests</CardTitle></CardHeader><CardContent className="space-y-3">{items.length?items.map((x:any)=><div key={x.id} className="flex justify-between rounded-xl bg-[#f3f6f3] p-3"><span>{x.diamond_count} Diamonds</span><Badge variant="outline">{x.status}</Badge></div>):<p className="text-sm text-[#68766e]">No requests yet.</p>}</CardContent></Card></div>}
function Transactions({data}:{data:any}){return <Card className="mt-8"><CardHeader><CardTitle>Your transactions</CardTitle></CardHeader><CardContent>{data.transactions.length?data.transactions.map((x:any)=><div className="flex justify-between border-b py-3" key={x.id}><div><p className="capitalize">{String(x.type).replaceAll("_"," ")}</p><p className="text-sm text-[#68766e]">{x.note||new Date(x.created_at).toLocaleString()}</p></div><b className={Number(x.amount_cents)>=0?"text-[#1b4d39]":"text-[#963f35]"}>{Number(x.amount_cents)>=0?"+":"−"}{money(Math.abs(Number(x.amount_cents||0)))}</b></div>):<p>No transactions yet.</p>}</CardContent></Card>}
function Center({text}:{text:string}){return <div className="grid min-h-screen place-items-center bg-[#f5f7f3] p-6 text-center">{text}</div>}
