// Generated by Bool from bool/entities/village_deposit_requests.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageDepositRequests {
  id: string;
  created_at: string;
  user_id: string;
  diamond_count: number;
  exchange_rate_cents: number;
  calculated_amount_cents: number;
  status: "pending" | "approved" | "rejected" | "cancelled";
  user_note: string | null;
  admin_note: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  completed_at: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_deposit_requests: EntityHandler<VillageDepositRequests>;
  }
}
