// Generated by Bool from bool/entities/village_purchases.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillagePurchases {
  id: string;
  created_at: string;
  amount: number;
  buyer: string;
  item_name: string;
  notes: string | null;
  status: "completed" | "refunded" | "revoked";
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_purchases: EntityHandler<VillagePurchases>;
  }
}
