// Generated by Bool from bool/entities/village_reserve_transactions.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageReserveTransactions {
  id: string;
  created_at: string;
  type: "deposit_received" | "withdrawal_paid" | "admin_addition" | "admin_removal" | "correction";
  diamond_amount: number;
  diamond_balance_before: number;
  diamond_balance_after: number;
  related_deposit_id: string | null;
  related_withdrawal_id: string | null;
  created_by: string | null;
  reason: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_reserve_transactions: EntityHandler<VillageReserveTransactions>;
  }
}
