// Generated by Bool from bool/entities/village_economy_snapshots.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageEconomySnapshots {
  id: string;
  created_at: string;
  currency_supply_cents: number;
  diamond_reserve_count: number;
  exchange_rate_cents: number;
  reserve_value_cents: number;
  backing_ratio: number | null;
  total_deposits_cents: number | null;
  total_withdrawals_cents: number | null;
  transfer_volume_cents: number | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_economy_snapshots: EntityHandler<VillageEconomySnapshots>;
  }
}
