// Generated by Bool from bool/entities/village_audit_logs.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageAuditLogs {
  id: string;
  created_at: string;
  actor: string;
  action: string;
  target: string | null;
  reason: string | null;
  metadata: unknown | null;
  created_at_source: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_audit_logs: EntityHandler<VillageAuditLogs>;
  }
}
