// Generated by Bool from bool/entities/village_transfers.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageTransfers {
  id: string;
  created_at: string;
  sender_user_id: string;
  recipient_user_id: string;
  amount_cents: number;
  note: string | null;
  status: "completed" | "reversed" | "cancelled";
  initiated_by: string | null;
  completed_at: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_transfers: EntityHandler<VillageTransfers>;
  }
}
