// Generated by Bool from bool/entities/village_balance_history.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageBalanceHistory {
  id: string;
  created_at: string;
  balance: number;
  balance_cents: number | null;
  source_id: string | null;
  source_transaction_id: string | null;
  source_type: string | null;
  type: string;
  user_id: string | null;
  username: string;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_balance_history: EntityHandler<VillageBalanceHistory>;
  }
}
