// Generated by Bool from bool/entities/village_economy_settings.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageEconomySettings {
  id: string;
  created_at: string;
  key: string;
  value: number;
  string_value: string | null;
  label: string;
  updated_by: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_economy_settings: EntityHandler<VillageEconomySettings>;
  }
}
