// Generated by Bool from bool/entities/village_announcements.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageAnnouncements {
  id: string;
  created_at: string;
  title: string;
  body: string | null;
  priority: "normal" | "important" | "urgent" | null;
  status: "draft" | "published" | "archived";
  starts_at: string | null;
  expires_at: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_announcements: EntityHandler<VillageAnnouncements>;
  }
}
