// Generated by Bool from bool/entities/village_marketplace.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageMarketplace {
  id: string;
  created_at: string;
  category: string;
  description: string | null;
  featured: boolean | null;
  image_path: string | null;
  name: string;
  price: number;
  status: "published" | "draft" | "archived";
  stock: number;
  unlimited_stock: boolean | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_marketplace: EntityHandler<VillageMarketplace>;
  }
}
