// Generated by Bool from bool/entities/village_transactions.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageTransactions {
  id: string;
  created_at: string;
  amount: number;
  amount_cents: number | null;
  balance_after: number | null;
  balance_before: number | null;
  balance_after_cents: number | null;
  balance_before_cents: number | null;
  created_by: string | null;
  metadata: unknown | null;
  note: string | null;
  related_transaction_id: string | null;
  transfer_id: string | null;
  deposit_id: string | null;
  withdrawal_id: string | null;
  status: "completed" | "reversed" | "cancelled";
  type: "diamond_deposit" | "diamond_withdrawal" | "transfer_sent" | "transfer_received" | "admin_credit" | "admin_debit" | "balance_adjustment" | "transfer_reversal" | "deposit_reversal" | "withdrawal_reversal" | "deposit" | "withdrawal" | "purchase" | "adjustment" | "refund" | "reversal";
  user_id: string | null;
  username: string;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_transactions: EntityHandler<VillageTransactions>;
  }
}
