// Generated by Bool from bool/entities/village_diamond_reserves.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageDiamondReserves {
  id: string;
  created_at: string;
  diamond_count: number;
  updated_by: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_diamond_reserves: EntityHandler<VillageDiamondReserves>;
  }
}
