// Generated by Bool from bool/entities/village_accounts.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageAccounts {
  id: string;
  created_at: string;
  user_id: string;
  balance_cents: number;
  banking_status: "active" | "frozen";
  updated_at_source: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_accounts: EntityHandler<VillageAccounts>;
  }
}
