// Generated by Bool from bool/entities/village_applications.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageApplications {
  id: string;
  created_at: string;
  admin_notes: string | null;
  applicant: string;
  job_title: string;
  message: string | null;
  status: "pending" | "reviewing" | "accepted" | "rejected" | "withdrawn";
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_applications: EntityHandler<VillageApplications>;
  }
}
