// Generated by Bool from bool/entities/village_users.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageUsers {
  id: string;
  created_at: string;
  username: string;
  normalized_username: string;
  display_name: string | null;
  role: "user" | "admin";
  status: "active" | "suspended" | "disabled";
  banking_status: "active" | "frozen";
  balance: number;
  must_change_password: boolean;
  last_seen_at: string | null;
  password_hash: string | null;
  freeze_reason: string | null;
  frozen_by: string | null;
  frozen_at: string | null;
  unfrozen_by: string | null;
  unfrozen_at: string | null;
  suspension_reason: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_users: EntityHandler<VillageUsers>;
  }
}
