// Generated by Bool from bool/entities/village_news.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageNews {
  id: string;
  created_at: string;
  title: string;
  subtitle: string | null;
  excerpt: string | null;
  body: string | null;
  category: string | null;
  cover_image_path: string | null;
  status: "published" | "draft" | "archived";
  featured: boolean | null;
  author: string | null;
  published_at: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_news: EntityHandler<VillageNews>;
  }
}
