// Generated by Bool from bool/entities/village_feature_controls.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageFeatureControls {
  id: string;
  created_at: string;
  key: string;
  enabled: boolean;
  label: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_feature_controls: EntityHandler<VillageFeatureControls>;
  }
}
