// Generated by Bool from bool/entities/village_jobs.jsonc — do not edit by hand.
import type { EntityHandler } from "bool-sdk";

export interface VillageJobs {
  id: string;
  created_at: string;
  title: string;
  department: string | null;
  short_description: string | null;
  full_description: string | null;
  compensation: string | null;
  location: string | null;
  status: "draft" | "open" | "closed" | "archived";
  applications: number;
  featured: boolean | null;
  applications_enabled: boolean | null;
  deadline: string | null;
}

declare module "bool-sdk" {
  interface EntitiesModule {
    village_jobs: EntityHandler<VillageJobs>;
  }
}
