import { createClient } from "@supabase/supabase-js";
import { createHash, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

const URL = process.env.SUPABASE_URL || "";
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "";
const COOKIE = "village_session";
const SESSION_DAYS = 14;
const sb = URL && KEY ? createClient(URL, KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
const ok=(res:any,data:any,status=200)=>res.status(status).json({success:true,data});
const fail=(res:any,status:number,message:string,code="ERROR")=>res.status(status).json({success:false,error:{code,message}});
const body=(req:any)=>typeof req.body==="string"?JSON.parse(req.body||"{}"):req.body||{};
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
const hashPassword=(password:string)=>{const salt=randomBytes(16).toString("hex");return `scrypt$${salt}$${scryptSync(password,salt,64).toString("hex")}`};
const verifyPassword=(password:string,stored:string)=>{try{const [kind,salt,hex]=stored.split("$");if(kind!=="scrypt"||!salt||!hex)return false;const a=scryptSync(password,salt,64),b=Buffer.from(hex,"hex");return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}};
function cookies(req:any){const out:any={};String(req.headers.cookie||"").split(";").forEach((p:string)=>{const i=p.indexOf("=");if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function setCookie(res:any,name:string,value:string,maxAge:number){res.setHeader("Set-Cookie",`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}; ${process.env.NODE_ENV==="production"?"Secure; ":""}`)}
async function session(req:any){if(!sb)return null;const token=cookies(req)[COOKIE];if(!token)return null;const {data:s}=await sb.from("village_user_sessions").select("id,user_id,expires_at,revoked_at").eq("token_hash",hash(token)).maybeSingle();if(!s||s.revoked_at||new Date(s.expires_at)<=new Date())return null;const {data:u}=await sb.from("village_users").select("id,username,normalized_username,display_name,role,status,banking_status,must_change_password").eq("id",s.user_id).maybeSingle();if(!u||u.status==="disabled")return null;await sb.from("village_user_sessions").update({last_used_at:new Date().toISOString()}).eq("id",s.id);return u}
async function requireUser(req:any,res:any){const u=await session(req);if(!u){fail(res,401,"Sign in required.","UNAUTHENTICATED");return null}if(u.status!=="active"){fail(res,403,"This account is suspended.","ACCOUNT_BLOCKED");return null}return u}
async function requireAdmin(req:any,res:any){const u=await requireUser(req,res);if(!u)return null;if(u.role!=="admin"){fail(res,403,"Administrator access required.","FORBIDDEN");return null}return u}
function safeUser(u:any){return {id:u.id,username:u.username,normalized_username:u.normalized_username,display_name:u.display_name,role:u.role,status:u.status,banking_status:u.banking_status,must_change_password:u.must_change_password}}
async function setting(key:string, fallback:number|string|null=null){if(!sb)return fallback;const {data}=await sb.from("village_economy_settings").select("value").eq("key",key).maybeSingle();return data?.value??fallback}
async function economy(){if(!sb)return {};const [{data:ac},{data:r}]=await Promise.all([sb.from("village_accounts").select("balance_cents"),sb.from("village_diamond_reserves").select("diamond_count").limit(1).maybeSingle()]);const supply=(ac||[]).reduce((s:any,x:any)=>s+Number(x.balance_cents||0),0);const diamonds=Number(r?.diamond_count||0);const rate=Number(await setting("diamond_rate",1000));const reserve=diamonds*rate;return {currency_supply_cents:supply,diamond_count:diamonds,diamond_rate_cents:rate,reserve_value_cents:reserve,backing_ratio:supply?reserve/supply*100:null}}
async function ensureBucket(){if(!sb)return;const {data}=await sb.storage.listBuckets();if(!(data||[]).some(b=>b.name==="public-media"))await sb.storage.createBucket("public-media",{public:true,fileSizeLimit:5242880})}
async function audit(actor:any,action:string,target?:string,reason?:string){if(!sb)return;await sb.from("village_audit_logs").insert({actor_user_id:actor.id,actor:actor.username,action,target:target||null,reason:reason||null})}

export default async function handler(req:any,res:any){
  try{
    const qpath = req.query?.path;
    const rawPath = Array.isArray(qpath)
      ? qpath.join("/")
      : typeof qpath === "string" && qpath.length
        ? qpath
        : String(req.url || req.path || "").split("?")[0].replace(/^\/api\/gateway\/?/, "");
    const path = "/" + String(rawPath).split("/").filter(Boolean).join("/");
    if(path==="/health") return ok(res,{configured:!!sb,app:"Village Central",server:true});
    if(!sb)return fail(res,503,"Server database configuration is missing. Add SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Vercel.","CONFIG_MISSING");

    if(path==="/setup/status"&&req.method==="GET"){const {count}=await sb.from("village_users").select("id",{count:"exact",head:true});return ok(res,{initialized:(count||0)>0,user_count:count||0})}
    if(path==="/bootstrap"&&req.method==="POST"){const b=body(req);if(!process.env.BOOTSTRAP_SECRET||b.secret!==process.env.BOOTSTRAP_SECRET)return fail(res,403,"Invalid bootstrap secret.");const names=["Anas","Samma","Youssef","Ahmad","Omar","Bisher","Abdullah","Mikyle"];const adminPass=b.omar_password||process.env.INITIAL_ADMIN_PASSWORD;if(!adminPass||String(adminPass).length<8)return fail(res,400,"Provide omar_password with at least 8 characters or INITIAL_ADMIN_PASSWORD.");for(const name of names){const normalized=name.toLowerCase();const {data:existing}=await sb.from("village_users").select("id").eq("normalized_username",normalized).maybeSingle();if(existing)continue;const usable=name==="Omar"?String(adminPass):String(b.passwords?.[name]||randomBytes(32).toString("hex"));const {data:u,error}=await sb.from("village_users").insert({username:name,normalized_username:normalized,display_name:name,role:name==="Omar"?"admin":"user",status:"active",banking_status:"active",password_hash:hashPassword(usable),must_change_password:name!=="Omar"}).select("id").single();if(error)throw error;await sb.from("village_accounts").insert({user_id:u.id,balance_cents:0});}await sb.from("village_economy_settings").upsert({key:"diamond_rate",value:"1000"},{onConflict:"key"});const {data:rr}=await sb.from("village_diamond_reserves").select("id").limit(1).maybeSingle();if(!rr)await sb.from("village_diamond_reserves").insert({diamond_count:0});await ensureBucket();return ok(res,{message:"Initialized. Omar can sign in; reset other users from Admin before use."})}

    if(path==="/auth/login"&&req.method==="POST"){const b=body(req), username=String(b.username||"").trim().toLowerCase(), password=String(b.password||"");if(!username||!password)return fail(res,400,"Enter a Minecraft username and password.");const {data:u}=await sb.from("village_users").select("*").eq("normalized_username",username).maybeSingle();if(!u||!verifyPassword(password,u.password_hash||""))return fail(res,401,"Invalid username or password.","BAD_LOGIN");if(u.status!=="active")return fail(res,403,u.status==="suspended"?"This account is suspended.":"This account is disabled.");const token=randomBytes(32).toString("base64url"),expires=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await sb.from("village_user_sessions").insert({user_id:u.id,token_hash:hash(token),expires_at:expires});await sb.from("village_users").update({last_login_at:new Date().toISOString()}).eq("id",u.id);setCookie(res,COOKIE,token,SESSION_DAYS*86400);return ok(res,{user:safeUser(u)})}
    if(path==="/auth/session"&&req.method==="GET"){const u=await session(req);return ok(res,{authenticated:!!u,user:u?safeUser(u):undefined})}
    if(path==="/auth/logout"&&req.method==="POST"){const token=cookies(req)[COOKIE];if(token)await sb.from("village_user_sessions").update({revoked_at:new Date().toISOString()}).eq("token_hash",hash(token));setCookie(res,COOKIE,"",0);return ok(res,{logged_out:true})}
    if(path==="/auth/change-password"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const b=body(req),pw=String(b.password||"");if(pw.length<8)return fail(res,400,"Password must be at least 8 characters.");await sb.from("village_users").update({password_hash:hashPassword(pw),must_change_password:false}).eq("id",u.id);return ok(res,{changed:true})}

    if(path==="/me/dashboard"&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const [{data:a},{data:t},{data:h},e]=await Promise.all([sb.from("village_accounts").select("*").eq("user_id",u.id).maybeSingle(),sb.from("village_transactions").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(20),sb.from("village_balance_history").select("*").eq("user_id",u.id).order("created_at",{ascending:true}).limit(500),economy()]);const tx=t||[];return ok(res,{balance_cents:Number(a?.balance_cents||0),received_cents:tx.filter((x:any)=>Number(x.amount_cents)>0).reduce((s:any,x:any)=>s+Number(x.amount_cents),0),sent_cents:Math.abs(tx.filter((x:any)=>Number(x.amount_cents)<0).reduce((s:any,x:any)=>s+Number(x.amount_cents),0)),transactions:tx.slice(0,8),balance_history:h||[],economy:e})}
    if(path==="/me/banking"&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const [{data:a},{data:users},{data:t},{data:d},{data:w}]=await Promise.all([sb.from("village_accounts").select("*").eq("user_id",u.id).maybeSingle(),sb.from("village_users").select("id,username,display_name,status,banking_status").eq("status","active").order("username"),sb.from("village_transactions").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(200),sb.from("village_deposit_requests").select("*").eq("user_id",u.id).order("created_at",{ascending:false}),sb.from("village_withdrawal_requests").select("*").eq("user_id",u.id).order("created_at",{ascending:false})]);return ok(res,{balance_cents:Number(a?.balance_cents||0),diamond_rate_cents:Number(await setting("diamond_rate",1000)),recipients:(users||[]).filter((x:any)=>x.id!==u.id&&x.banking_status!=="disabled"),transactions:t||[],deposits:d||[],withdrawals:w||[]})}

    if(path==="/transfers/send"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;if(u.banking_status==="frozen")return fail(res,403,"Your banking account is frozen.");const b=body(req),amount=Number(b.amount_cents);if(!b.recipient_user_id||!Number.isInteger(amount)||amount<=0||b.recipient_user_id===u.id)return fail(res,400,"Choose a valid recipient and amount.");const {data:r,error}=await sb.rpc("vc_transfer",{p_sender:u.id,p_recipient:b.recipient_user_id,p_amount:amount,p_note:String(b.note||"").slice(0,300),p_initiated_by:u.id});if(error)return fail(res,400,error.message);return ok(res,{transfer_id:r})}
    if(path==="/deposits/request"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;if(u.banking_status==="frozen")return fail(res,403,"Your banking account is frozen.");const n=Math.floor(Number(body(req).diamond_count));if(!Number.isInteger(n)||n<=0)return fail(res,400,"Diamond count must be a positive whole number.");const rate=Number(await setting("diamond_rate",1000));const {data,error}=await sb.from("village_deposit_requests").insert({user_id:u.id,diamond_count:n,exchange_rate_cents:rate,calculated_amount_cents:n*rate,status:"pending"}).select().single();if(error)throw error;return ok(res,data)}
    if(path==="/withdrawals/request"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;if(u.banking_status==="frozen")return fail(res,403,"Your banking account is frozen.");const n=Math.floor(Number(body(req).diamond_count));if(!Number.isInteger(n)||n<=0)return fail(res,400,"Diamond count must be a positive whole number.");const rate=Number(await setting("diamond_rate",1000));const amount=n*rate;const {data:a}=await sb.from("village_accounts").select("balance_cents").eq("user_id",u.id).maybeSingle();if(Number(a?.balance_cents||0)<amount)return fail(res,400,"Insufficient balance.");const {data,error}=await sb.from("village_withdrawal_requests").insert({user_id:u.id,diamond_count:n,exchange_rate_cents:rate,amount_cents:amount,status:"pending"}).select().single();if(error)throw error;return ok(res,data)}

    if(path==="/news"&&req.method==="GET"){const {data,error}=await sb.from("village_news").select("*").eq("status","published").order("created_at",{ascending:false});if(error)throw error;return ok(res,data||[])}
    if(path==="/jobs"&&req.method==="GET"){const {data,error}=await sb.from("village_jobs").select("*").eq("status","open").order("created_at",{ascending:false});if(error)throw error;return ok(res,data||[])}
    const jobApply=path.match(/^\/jobs\/([^/]+)\/apply$/);if(jobApply&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const jobId=jobApply[1],b=body(req);const {data:j}=await sb.from("village_jobs").select("id,title,status").eq("id",jobId).maybeSingle();if(!j||j.status!=="open")return fail(res,404,"Job is not open.");const {data:existing}=await sb.from("village_applications").select("id").eq("job_id",jobId).eq("user_id",u.id).neq("status","withdrawn").maybeSingle();if(existing)return fail(res,409,"You already applied to this job.");const {data,error}=await sb.from("village_applications").insert({job_id:jobId,user_id:u.id,applicant:u.username,job_title:j.title,message:String(b.message||"").slice(0,2000),status:"pending"}).select().single();if(error)throw error;return ok(res,data)}

    if(path==="/admin/overview"&&req.method==="GET"){const a=await requireAdmin(req,res);if(!a)return;const tables=["village_users","village_accounts","village_transactions","village_transfers","village_deposit_requests","village_withdrawal_requests","village_news","village_jobs","village_applications","village_audit_logs"];const out:any={};for(const t of tables){const {data,error}=await sb.from(t).select("*").order("created_at",{ascending:false}).limit(500);if(error)throw error;out[t]=data||[]}out.economy=await economy();const {data:r}=await sb.from("village_reserve_transactions").select("*").order("created_at",{ascending:false}).limit(500);out.village_reserve_transactions=r||[];const {data:s}=await sb.from("village_economy_snapshots").select("*").order("created_at",{ascending:true}).limit(1000);out.village_economy_snapshots=s||[];return ok(res,out)}
    if(path==="/admin/users"&&req.method==="GET"){const a=await requireAdmin(req,res);if(!a)return;const {data:u}=await sb.from("village_users").select("id,username,normalized_username,display_name,role,status,banking_status,must_change_password,created_at,last_login_at").order("username");const {data:ac}=await sb.from("village_accounts").select("*");return ok(res,{users:u||[],accounts:ac||[]})}
    if(path==="/admin/users/create"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req),username=String(b.username||"").trim(),pw=String(b.password||"");if(!/^[A-Za-z0-9_]{3,16}$/.test(username))return fail(res,400,"Use a valid Minecraft username (3-16 letters, numbers, underscore).");if(pw.length<8)return fail(res,400,"Temporary password must be at least 8 characters.");const {data:u,error}=await sb.from("village_users").insert({username,normalized_username:username.toLowerCase(),display_name:b.display_name||username,role:b.role==="admin"?"admin":"user",status:"active",banking_status:"active",password_hash:hashPassword(pw),must_change_password:true}).select().single();if(error)return fail(res,400,error.message);await sb.from("village_accounts").insert({user_id:u.id,balance_cents:Number(b.starting_balance_cents||0)});await audit(a,"Create user",username);return ok(res,safeUser(u))}
    const userAct=path.match(/^\/admin\/users\/([^/]+)\/(freeze|unfreeze|suspend|unsuspend|disable|enable|role|reset-password)$/);if(userAct&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const [_,id,act]=userAct,b=body(req);if(act==="freeze"||act==="unfreeze")await sb.from("village_users").update({banking_status:act==="freeze"?"frozen":"active",freeze_reason:act==="freeze"?String(b.reason||"Administrative freeze"):null}).eq("id",id);else if(["suspend","unsuspend","disable","enable"].includes(act))await sb.from("village_users").update({status:act==="suspend"?"suspended":act==="disable"?"disabled":"active"}).eq("id",id);else if(act==="role")await sb.from("village_users").update({role:b.role==="admin"?"admin":"user"}).eq("id",id);else if(act==="reset-password"){const pw=String(b.password||"");if(pw.length<8)return fail(res,400,"Temporary password must be at least 8 characters.");await sb.from("village_users").update({password_hash:hashPassword(pw),must_change_password:true}).eq("id",id);await sb.from("village_user_sessions").update({revoked_at:new Date().toISOString()}).eq("user_id",id)}await audit(a,act,id,String(b.reason||""));return ok(res,{updated:true})}
    if(path==="/admin/balance/adjust"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req),amount=Number(b.amount_cents);if(!b.user_id||!Number.isInteger(amount)||!b.kind||!String(b.reason||"").trim())return fail(res,400,"User, amount, kind and reason are required.");const {data,error}=await sb.rpc("vc_admin_adjust_balance",{p_actor:a.id,p_target:b.user_id,p_amount:amount,p_kind:b.kind,p_reason:String(b.reason)});if(error)return fail(res,400,error.message);return ok(res,{balance_cents:data})}
    if(path==="/admin/transfers"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req),amount=Number(b.amount_cents);if(!b.sender_user_id||!b.recipient_user_id||!Number.isInteger(amount)||amount<=0||!String(b.reason||"").trim())return fail(res,400,"From, to, amount and reason are required.");const {data,error}=await sb.rpc("vc_transfer",{p_sender:b.sender_user_id,p_recipient:b.recipient_user_id,p_amount:amount,p_note:String(b.reason),p_initiated_by:a.id});if(error)return fail(res,400,error.message);await audit(a,"Admin transfer",`${b.sender_user_id}->${b.recipient_user_id}`,b.reason);return ok(res,{transfer_id:data})}
    const depAct=path.match(/^\/admin\/deposits\/([^/]+)\/(approve|reject)$/);if(depAct&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const {data,error}=await sb.rpc("vc_review_deposit",{p_actor:a.id,p_request:depAct[1],p_approve:depAct[2]==="approve",p_reason:String(body(req).reason||"")});if(error)return fail(res,400,error.message);return ok(res,{result:data})}
    const wdAct=path.match(/^\/admin\/withdrawals\/([^/]+)\/(approve|reject)$/);if(wdAct&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const {data,error}=await sb.rpc("vc_review_withdrawal",{p_actor:a.id,p_request:wdAct[1],p_approve:wdAct[2]==="approve",p_reason:String(body(req).reason||"")});if(error)return fail(res,400,error.message);return ok(res,{result:data})}
    if(path==="/admin/reserves/adjust"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req),amount=Number(b.amount);if(!Number.isInteger(amount)||!String(b.reason||"").trim())return fail(res,400,"Whole-number adjustment and reason required.");const {data,error}=await sb.rpc("vc_adjust_reserve",{p_actor:a.id,p_delta:amount,p_reason:String(b.reason)});if(error)return fail(res,400,error.message);return ok(res,{diamond_count:data})}
    if(path==="/admin/economy/rate"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const rate=Number(body(req).rate_cents);if(!Number.isInteger(rate)||rate<=0)return fail(res,400,"Rate must be positive cents.");await sb.from("village_economy_settings").upsert({key:"diamond_rate",value:String(rate),updated_by:a.id,updated_at:new Date().toISOString()},{onConflict:"key"});await audit(a,"Change diamond rate",String(rate));return ok(res,{rate_cents:rate})}

    if(path==="/admin/news"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req);if(!String(b.title||"").trim())return fail(res,400,"Title required.");const {data,error}=await sb.from("village_news").insert({title:b.title,subtitle:b.subtitle||"",excerpt:b.excerpt||"",body:b.body||"",category:b.category||"Community",status:b.status||"draft",author:a.username,image_url:b.image_url||null}).select().single();if(error)throw error;await audit(a,"Create news",data.id);return ok(res,data)}
    const newsId=path.match(/^\/admin\/news\/([^/]+)$/);if(newsId&&(req.method==="PATCH"||req.method==="DELETE")){const a=await requireAdmin(req,res);if(!a)return;if(req.method==="DELETE"){await sb.from("village_news").delete().eq("id",newsId[1]);await audit(a,"Delete news",newsId[1]);return ok(res,{deleted:true})}const {data,error}=await sb.from("village_news").update(body(req)).eq("id",newsId[1]).select().single();if(error)throw error;await audit(a,"Edit news",newsId[1]);return ok(res,data)}
    if(path==="/admin/jobs"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req);if(!String(b.title||"").trim())return fail(res,400,"Title required.");const {data,error}=await sb.from("village_jobs").insert({title:b.title,department:b.department||"Village Central",short_description:b.short_description||"",full_description:b.full_description||"",compensation:b.compensation||"",location:b.location||"",status:b.status||"draft",image_url:b.image_url||null,created_by:a.id}).select().single();if(error)throw error;await audit(a,"Create job",data.id);return ok(res,data)}
    const jobId=path.match(/^\/admin\/jobs\/([^/]+)$/);if(jobId&&(req.method==="PATCH"||req.method==="DELETE")){const a=await requireAdmin(req,res);if(!a)return;if(req.method==="DELETE"){await sb.from("village_jobs").delete().eq("id",jobId[1]);await audit(a,"Delete job",jobId[1]);return ok(res,{deleted:true})}const {data,error}=await sb.from("village_jobs").update(body(req)).eq("id",jobId[1]).select().single();if(error)throw error;await audit(a,"Edit job",jobId[1]);return ok(res,data)}
    const appId=path.match(/^\/admin\/applications\/([^/]+)$/);if(appId&&req.method==="PATCH"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req);const {data,error}=await sb.from("village_applications").update({status:b.status,admin_notes:b.admin_notes}).eq("id",appId[1]).select().single();if(error)throw error;await audit(a,"Review application",appId[1],b.status);return ok(res,data)}
    if(path==="/admin/media/upload"&&req.method==="POST"){const a=await requireAdmin(req,res);if(!a)return;const b=body(req),mime=String(b.mime||""),filename=String(b.filename||"upload");if(!/^image\/(png|jpeg|webp|gif)$/.test(mime))return fail(res,400,"Only PNG, JPEG, WebP or GIF images are allowed.");const base64=String(b.data||"").replace(/^data:[^;]+;base64,/,"");const buf=Buffer.from(base64,"base64");if(!buf.length||buf.length>5*1024*1024)return fail(res,400,"Image must be between 1 byte and 5 MB.");await ensureBucket();const ext=mime.split("/")[1].replace("jpeg","jpg"),pathName=`uploads/${Date.now()}-${randomBytes(6).toString("hex")}.${ext}`;const {error}=await sb.storage.from("public-media").upload(pathName,buf,{contentType:mime,upsert:false});if(error)throw error;const {data:url}=sb.storage.from("public-media").getPublicUrl(pathName);await audit(a,"Upload media",filename);return ok(res,{path:pathName,url:url.publicUrl})}

    return fail(res,404,"API route not found.","NOT_FOUND");
  }catch(e:any){console.error(e);return fail(res,500,e?.message||"Unexpected server error.","SERVER_ERROR")}
}
